"""empty message

Revision ID: 43a870ca369f
Revises: 
Create Date: 2023-03-19 16:24:47.278964

"""
from alembic import op
import sqlalchemy as sa
from electricity_board.models.connection_request import ConnectionRequest


# revision identifiers, used by Alembic.
revision = '43a870ca369f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('ownership', sa.String(length=100), nullable=True),
    sa.Column('govtid_type', sa.String(length=100), nullable=True),
    sa.Column('id_number', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('load_applied', sa.String(length=100), nullable=True),
    sa.Column('date_of_application', sa.Date, nullable=True),
    sa.Column('Date_of_approval', sa.Date, nullable=True),
    sa.Column('modified_date', sa.Date, nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('reviewer_id', sa.String(length=100), nullable=True),
    sa.Column('reviewer_name', sa.String(length=100), nullable=True),
    sa.Column('reviewer_comments', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connection_request')
    # ### end Alembic commands ###
