export const GET_CONNECTION_REQUEST = 'GET_CONNECTION_REQUEST';
export const GET_CONNECTION_SUCCESS = 'GET_CONNECTION_SUCCESS';
export const GET_CONNECTION_FAIL = 'GET_CONNECTION_FAIL';

export const UPDATE_CONNECTION_REQUEST = 'UPDATE_CONNECTION_REQUEST';
export const UPDATE_CONNECTION_SUCCESS = 'UPDATE_CONNECTION_SUCCESS';
export const UPDATE_CONNECTION_FAIL = 'UPDATE_CONNECTION_FAIL';

